(function(){
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const unique=v=>[...new Set(v.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ms',{numeric:true}));
  const coreSubjects=['BM','BI','MM','SAINS','SEJARAH'];
  let portal={records:[],teacherAssignments:[],session:'',activity:''};
  let auth=null,workspace={groups:[],individuals:[],programs:[],dialogTasks:[]},activeTab='kelompok',slides=[],slideIndex=0;

  function apiPost(payload){return fetch(window.SAP_TEMIN_API_BASE,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)}).then(r=>r.json()).then(data=>{if(!data.ok)throw new Error(data.error||'Permintaan gagal.');return data});}
  function credentials(){return {teacherEmail:auth?.email||'',teacherPin:auth?.pin||''};}
  function setStatus(selector,message,error=false){const el=$(selector);if(!el)return;el.textContent=message;el.classList.toggle('error',error)}
  function today(){return new Date().toISOString().slice(0,10)}
  function assignmentsForTeacher(){if(!auth)return[];return portal.teacherAssignments.filter(x=>String(x.teacherEmail||'').toLowerCase()===auth.email.toLowerCase()&&x.role==='GURU SUBJEK')}
  function availableRecords(){const assigned=assignmentsForTeacher();if(!assigned.length)return portal.records;return portal.records.filter(r=>assigned.some(a=>String(a.subject)===String(r.subject)&&Number(a.year)===Number(r.year)&&String(a.className).toUpperCase()===String(r.className).toUpperCase()))}

  function subjectOptions(){return unique(availableRecords().map(r=>r.subject)).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
  function yearOptions(subject){return unique(availableRecords().filter(r=>!subject||r.subject===subject).map(r=>String(r.year))).map(v=>`<option value="${v}">Tahun ${v}</option>`).join('')}
  function classOptions(subject,year){return unique(availableRecords().filter(r=>(!subject||r.subject===subject)&&(!year||Number(r.year)===Number(year))).map(r=>r.className)).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
  function matchingPupils(form){const subject=form.subject.value,year=form.year.value,klass=form.elements.className.value,tp=form.originalTp.value;return availableRecords().filter(r=>r.subject===subject&&Number(r.year)===Number(year)&&r.className===klass&&(!tp||r.tp===tp)).sort((a,b)=>a.studentName.localeCompare(b.studentName,'ms'))}

  function renderGroupForm(){
    $('#workspace-content').innerHTML=`<section class="panel action-form-panel"><div class="panel-title"><div><small>PILIHAN UTAMA</small><h3>Intervensi Mengikut Kelompok</h3><p class="panel-help">Pilih kelas dan TP. Nama murid disenaraikan automatik—guru hanya semak dan simpan satu tindakan untuk seluruh kelompok.</p></div><span class="recommended-chip">Disyorkan</span></div><form id="group-intervention-form" class="workspace-form"><div class="form-grid"><label>Mata Pelajaran<select name="subject" required><option value="">Pilih subjek</option>${subjectOptions()}</select></label><label>Tahun<select name="year" required><option value="">Pilih tahun</option></select></label><label>Kelas<select name="className" required><option value="">Pilih kelas</option></select></label><label>Kelompok TP<select name="originalTp" required><option value="TP2">TP2</option><option value="TP1">TP1</option><option value="TP3">TP3</option><option value="TP4">TP4</option><option value="TP5">TP5</option><option value="TP6">TP6</option></select></label></div><section class="pupil-picker"><header><div><small>MURID DALAM KELOMPOK</small><strong id="group-pupil-count">0 murid</strong></div><button id="btn-toggle-pupils" class="btn btn-light compact-btn" type="button">Pilih Semua</button></header><div id="group-pupil-list" class="pupil-check-grid"><div class="empty-state">Pilih subjek, tahun dan kelas dahulu.</div></div></section><div class="form-grid"><label class="full">Isu / Kemahiran<textarea name="issue" required placeholder="Contoh: Belum menguasai operasi bahagi nombor bulat"></textarea></label><div class="full smart-action-row"><button class="btn btn-smart" id="btn-smart-group" type="button">✨ Cadangan Pintar</button><small>Cadangan boleh diubah mengikut pertimbangan guru.</small></div><label class="full">Objektif<textarea name="objective" required></textarea></label><label class="full">Aktiviti Intervensi<textarea name="interventionAction" required></textarea></label><label class="full">Bahan<input name="materials" placeholder="Contoh: kad imbas, lembaran berperingkat"></label><label>Tarikh Mula<input name="startDate" type="date" value="${today()}"></label><label>Tarikh Semakan<input name="reviewDate" type="date"></label><label class="full">Sasaran<input name="target" placeholder="Contoh: 8 daripada 10 murid mencapai sekurang-kurangnya TP3"></label><label class="full">Kaedah Penilaian<input name="assessmentMethod" placeholder="Contoh: latihan 5 item dan pemerhatian guru"></label><label>Status<select name="status"><option>BELUM MULA</option><option>SEDANG DILAKSANAKAN</option><option>SELESAI</option></select></label></div><button class="btn btn-primary" type="submit">Simpan Intervensi Kelompok</button><p id="group-form-status" class="form-status"></p></form></section>`;
    bindGroupForm();
  }
  function refreshGroupSelectors(form,source){const subject=form.subject.value,year=form.year.value;if(source==='subject'){form.year.innerHTML='<option value="">Pilih tahun</option>'+yearOptions(subject);form.elements.className.innerHTML='<option value="">Pilih kelas</option>'}if(source==='year')form.elements.className.innerHTML='<option value="">Pilih kelas</option>'+classOptions(subject,year);renderPupilPicker(form)}
  function renderPupilPicker(form){const list=$('#group-pupil-list'),pupils=matchingPupils(form);$('#group-pupil-count').textContent=`${pupils.length} murid`;list.innerHTML=pupils.length?pupils.map((r,i)=>`<label><input type="checkbox" name="member" value="${i}" checked data-name="${esc(r.studentName)}" data-key="${esc(r.studentKey||'')}" data-tp="${esc(r.tp)}"><span><b>${esc(r.studentName)}</b><small>${esc(r.tp)}</small></span></label>`).join(''):'<div class="empty-state">Tiada murid bagi pilihan ini.</div>'}
  function smartSuggestion(form){const subject=form.subject.value||'mata pelajaran ini',tp=form.originalTp?.value||'TP2',count=form.querySelectorAll('[name="member"]:checked').length||'murid terpilih',issue=form.issue.value.trim()||'kemahiran yang dikenal pasti';form.objective.value=`Meningkatkan penguasaan ${count} murid ${tp} dalam ${issue.toLowerCase()} melalui bimbingan berfokus.`;form.interventionAction.value=`Melaksanakan bimbingan kumpulan kecil secara berperingkat, penerangan semula menggunakan contoh mudah, latihan berpandu dan latihan kendiri bagi ${subject}. Maklum balas diberikan serta-merta berdasarkan kesilapan murid.`;form.materials.value='Bahan visual/manipulatif, kad panduan dan lembaran latihan berperingkat';form.target.value=`Sekurang-kurangnya 80% murid kelompok menunjukkan peningkatan dan mencapai tahap penguasaan yang disasarkan.`;form.assessmentMethod.value='Pemerhatian, soal jawab dan penilaian semula ringkas selepas intervensi.'}
  function bindGroupForm(){const form=$('#group-intervention-form');form.subject.onchange=()=>refreshGroupSelectors(form,'subject');form.year.onchange=()=>refreshGroupSelectors(form,'year');form.elements.className.onchange=()=>renderPupilPicker(form);form.originalTp.onchange=()=>renderPupilPicker(form);$('#btn-smart-group').onclick=()=>smartSuggestion(form);$('#btn-toggle-pupils').onclick=()=>{const boxes=[...form.querySelectorAll('[name="member"]')],all=boxes.every(x=>x.checked);boxes.forEach(x=>x.checked=!all);$('#btn-toggle-pupils').textContent=all?'Pilih Semua':'Kosongkan'};form.onsubmit=async e=>{e.preventDefault();const members=[...form.querySelectorAll('[name="member"]:checked')].map(x=>({studentName:x.dataset.name,studentKey:x.dataset.key,tpBefore:x.dataset.tp}));if(!members.length)return setStatus('#group-form-status','Pilih sekurang-kurangnya seorang murid.',true);const fd=Object.fromEntries(new FormData(form).entries());delete fd.member;setStatus('#group-form-status','Menyimpan…');try{const data=await apiPost({action:'save_group_intervention',session:portal.session,members,...fd,...credentials()});setStatus('#group-form-status',`Berjaya disimpan untuk ${data.pupils} murid.`);await loadWorkspace();setTimeout(renderGroupForm,500)}catch(err){setStatus('#group-form-status',err.message,true)}}}

  function renderIndividualForm(){
    $('#workspace-content').innerHTML=`<section class="panel action-form-panel"><div class="panel-title"><div><small>PILIHAN TAMBAHAN</small><h3>Intervensi Individu</h3><p class="panel-help">Gunakan hanya apabila seseorang murid memerlukan bimbingan khusus yang berbeza daripada kelompok.</p></div></div><form id="individual-form" class="workspace-form"><div class="form-grid"><label>Mata Pelajaran<select name="subject" required><option value="">Pilih subjek</option>${subjectOptions()}</select></label><label>Tahun<select name="year" required><option value="">Pilih tahun</option></select></label><label>Kelas<select name="className" required><option value="">Pilih kelas</option></select></label><label>Murid<select name="studentChoice" required><option value="">Pilih murid</option></select></label><input name="studentName" type="hidden"><input name="studentKey" type="hidden"><input name="originalTp" type="hidden"><label class="full">Isu / Kemahiran<textarea name="issue" required></textarea></label><label class="full">Objektif<textarea name="objective" required></textarea></label><label class="full">Aktiviti Intervensi<textarea name="interventionAction" required></textarea></label><label>Tarikh Mula<input name="startDate" type="date" value="${today()}"></label><label>Tarikh Semakan<input name="reviewDate" type="date"></label><label class="full">Sasaran<input name="target"></label><label>Status<select name="status"><option>BELUM MULA</option><option>SEDANG DILAKSANAKAN</option><option>SELESAI</option></select></label></div><div class="smart-action-row"><button id="btn-smart-individual" class="btn btn-smart" type="button">✨ Cadangan Pintar</button></div><button class="btn btn-primary" type="submit">Simpan Intervensi Individu</button><p id="individual-form-status" class="form-status"></p></form></section>`;
    const form=$('#individual-form');form.subject.onchange=()=>{form.year.innerHTML='<option value="">Pilih tahun</option>'+yearOptions(form.subject.value)};form.year.onchange=()=>{form.elements.className.innerHTML='<option value="">Pilih kelas</option>'+classOptions(form.subject.value,form.year.value)};form.elements.className.onchange=()=>{const pupils=availableRecords().filter(r=>r.subject===form.subject.value&&Number(r.year)===Number(form.year.value)&&r.className===form.elements.className.value).sort((a,b)=>a.studentName.localeCompare(b.studentName,'ms'));form.studentChoice.innerHTML='<option value="">Pilih murid</option>'+pupils.map((r,i)=>`<option value="${i}" data-name="${esc(r.studentName)}" data-key="${esc(r.studentKey||'')}" data-tp="${r.tp}">${esc(r.studentName)} · ${r.tp}</option>`).join('');form.studentChoice._pupils=pupils};form.studentChoice.onchange=()=>{const r=form.studentChoice._pupils?.[Number(form.studentChoice.value)];if(r){form.studentName.value=r.studentName;form.studentKey.value=r.studentKey||'';form.originalTp.value=r.tp}};$('#btn-smart-individual').onclick=()=>smartSuggestion(form);form.onsubmit=async e=>{e.preventDefault();setStatus('#individual-form-status','Menyimpan…');try{await apiPost({action:'save_individual_intervention',session:portal.session,...Object.fromEntries(new FormData(form).entries()),...credentials()});setStatus('#individual-form-status','Intervensi individu berjaya disimpan.');await loadWorkspace()}catch(err){setStatus('#individual-form-status',err.message,true)}}
  }

  function renderProgramForm(){
    $('#workspace-content').innerHTML=`<section class="panel action-form-panel"><div class="panel-title"><div><small>PANITIA</small><h3>Program Peningkatan Akademik</h3><p class="panel-help">Satu rekod ringkas yang boleh dikemas kini selepas program selesai.</p></div></div><form id="program-form" class="workspace-form"><div class="form-grid"><label>Mata Pelajaran<select name="subject" required><option value="">Pilih subjek</option>${subjectOptions()}</select></label><label>Nama Program<input name="programName" required placeholder="Contoh: Klinik Penguasaan Asas"></label><label class="full">Isu<textarea name="issue" required></textarea></label><label class="full">Objektif<textarea name="objective" required></textarea></label><label class="full">Kumpulan Sasaran<input name="targetGroup" placeholder="Contoh: Murid TP1–TP2 Tahun 4"></label><label>Tarikh Mula<input name="startDate" type="date"></label><label>Tarikh Tamat<input name="endDate" type="date"></label><label class="full">Aktiviti<textarea name="activities"></textarea></label><label class="full">Petunjuk Kejayaan<input name="successIndicator" placeholder="Contoh: 80% murid mencapai sekurang-kurangnya TP3"></label><label>Status<select name="status"><option>DIRANCANG</option><option>SEDANG DILAKSANAKAN</option><option>SELESAI</option></select></label><label class="full">Pautan Bukti<input name="evidenceUrl" type="url" placeholder="Google Drive / laporan program (jika ada)"></label></div><button class="btn btn-primary" type="submit">Simpan Program Panitia</button><p id="program-form-status" class="form-status"></p></form></section>`;const form=$('#program-form');form.onsubmit=async e=>{e.preventDefault();setStatus('#program-form-status','Menyimpan…');try{await apiPost({action:'save_panitia_program',session:portal.session,...Object.fromEntries(new FormData(form).entries()),...credentials()});setStatus('#program-form-status','Program panitia berjaya disimpan.');await loadWorkspace()}catch(err){setStatus('#program-form-status',err.message,true)}}
  }
  function renderStatus(){const cards=[...workspace.groups.map(x=>({...x,type:'Kelompok',title:x.groupName,meta:`${x.subject} · Tahun ${x.year} ${x.className} · ${x.pupilCount} murid`})),...workspace.individuals.map(x=>({...x,type:'Individu',title:x.studentName,meta:`${x.subject} · Tahun ${x.year} ${x.className}`})),...workspace.programs.map(x=>({...x,type:'Program Panitia',title:x.programName,meta:x.subject}))];$('#workspace-content').innerHTML=`<section class="panel"><div class="panel-title"><div><small>PEMANTAUAN KENDIRI</small><h3>Status Tindakan Saya</h3><p class="panel-help">Senarai ini membantu guru mengingati tindakan dan tarikh semakan.</p></div><span class="session-badge">${cards.length} rekod</span></div><div class="action-status-list">${cards.length?cards.map(x=>`<article><div><small>${esc(x.type)}</small><h4>${esc(x.title)}</h4><p>${esc(x.meta)}</p></div><div><span class="action-status">${esc(x.status)}</span>${x.reviewDate?`<time>Semakan: ${esc(x.reviewDate)}</time>`:''}</div></article>`).join(''):'<div class="empty-state">Belum ada tindakan direkodkan.</div>'}</div></section>`}
  function renderWorkspace(){document.querySelectorAll('.workspace-tab').forEach(b=>b.classList.toggle('active',b.dataset.workspaceTab===activeTab));if(activeTab==='kelompok')renderGroupForm();if(activeTab==='individu')renderIndividualForm();if(activeTab==='program')renderProgramForm();if(activeTab==='status')renderStatus()}
  async function loadWorkspace(){const data=await apiPost({action:'get_teacher_workspace',session:portal.session,...credentials()});workspace=data;auth.name=data.teacher.name;auth.role=data.teacher.role;$('#workspace-teacher-name').textContent=auth.name;$('#workspace-teacher-role').textContent=auth.role;renderWorkspace();return data}

  function subjectSummary(subject){const rows=portal.records.filter(r=>r.subject===subject),mastered=rows.filter(r=>Number(String(r.tp).replace(/\D/g,''))>=3).length,students=new Set(rows.map(r=>`${r.studentName}|${r.year}|${r.className}`)).size;return {subject,records:rows.length,students,mastered,notMastered:rows.length-mastered,rate:rows.length?mastered/rows.length*100:0}}
  function openDialogBuilder(){const box=$('#dialog-builder');const subjects=unique(portal.records.map(r=>r.subject));$('#dialog-date').value=today();$('#dialog-subject-options').innerHTML=subjects.map(s=>`<label><input type="checkbox" value="${esc(s)}" ${coreSubjects.includes(String(s).toUpperCase())?'checked':''}><span>${esc(s)}</span></label>`).join('');box.classList.remove('hidden');box.setAttribute('aria-hidden','false')}
  function closeDialogBuilder(){$('#dialog-builder').classList.add('hidden');$('#dialog-builder').setAttribute('aria-hidden','true')}
  function generateDialog(){const selected=[...$('#dialog-subject-options').querySelectorAll('input:checked')].map(x=>x.value);if(!selected.length)return alert('Pilih sekurang-kurangnya satu mata pelajaran.');const date=$('#dialog-date').value,purpose=$('#dialog-purpose').value||'Dialog Prestasi Sekolah';const all=portal.records,mastered=all.filter(r=>Number(String(r.tp).replace(/\D/g,''))>=3).length,studentCount=new Set(all.map(r=>`${r.studentName}|${r.year}|${r.className}`)).size;slides=[`<article class="dp-slide cover"><small>SEKOLAH KEBANGSAAN TEMIN</small><h1>Dialog Prestasi PBD</h1><p>${esc(purpose)}</p><strong>${date?new Date(date+'T00:00:00').toLocaleDateString('ms-MY',{day:'numeric',month:'long',year:'numeric'}):''}</strong><em>Sesi ${esc(portal.session)}</em></article>`,`<article class="dp-slide"><small>PRESTASI KESELURUHAN SEKOLAH</small><h2>Rumusan Eksekutif</h2><div class="dp-kpi-grid"><div><span>Jumlah Murid</span><b>${studentCount}</b></div><div><span>Rekod Pentaksiran</span><b>${all.length}</b></div><div class="good"><span>Menguasai</span><b>${all.length?(mastered/all.length*100).toFixed(1):0}%</b></div><div class="attention"><span>Belum Menguasai</span><b>${all.length?((all.length-mastered)/all.length*100).toFixed(1):0}%</b></div></div></article>`,...selected.map(subject=>{const s=subjectSummary(subject),programs=workspace.programs.filter(p=>p.subject===subject),groups=workspace.groups.filter(g=>g.subject===subject);return `<article class="dp-slide"><small>ANALISIS MATA PELAJARAN</small><h2>${esc(subject)}</h2><div class="dp-subject-layout"><div class="dp-donut" style="--rate:${s.rate.toFixed(1)}"><strong>${s.rate.toFixed(1)}%</strong><span>Menguasai</span></div><div class="dp-facts"><p><b>${s.students}</b><span>murid</span></p><p><b>${s.mastered}</b><span>rekod Menguasai</span></p><p><b>${s.notMastered}</b><span>rekod Belum Menguasai</span></p></div></div><section class="dp-action-summary"><h3>Tindakan direkodkan</h3><p>${groups.length} intervensi kelompok · ${programs.length} program panitia</p>${programs.slice(0,3).map(p=>`<span>${esc(p.programName)} — ${esc(p.status)}</span>`).join('')||'<span>Belum ada program panitia direkodkan.</span>'}</section></article>`}),`<article class="dp-slide"><small>TINDAKAN SUSULAN</small><h2>Komitmen Sekolah</h2><div class="dp-commitments"><p>✓ Melaksanakan intervensi kelompok mengikut keperluan murid.</p><p>✓ Memantau perkembangan dan membuat penilaian semula.</p><p>✓ Menilai keberkesanan program panitia berdasarkan data sebelum dan selepas.</p><p>✓ Melaporkan status tindakan dalam sesi Dialog Prestasi berikutnya.</p></div></article>`];slideIndex=0;closeDialogBuilder();showSlide();$('#dialog-presentation').classList.remove('hidden');$('#dialog-presentation').setAttribute('aria-hidden','false');document.body.classList.add('dialog-presenting')}
  function showSlide(){const box=$('#dialog-slides');box.innerHTML=slides[slideIndex]||'';$('#dialog-slide-counter').textContent=`${slideIndex+1} / ${slides.length}`;$('#btn-dialog-prev').disabled=slideIndex===0;$('#btn-dialog-next').disabled=slideIndex===slides.length-1}
  function printDialog(){if(!slides.length)return;$('#dialog-slides').innerHTML=slides.join('');document.body.classList.add('dialog-print-all');setTimeout(()=>window.print(),80)}
  function exitPresentation(){$('#dialog-presentation').classList.add('hidden');$('#dialog-presentation').setAttribute('aria-hidden','true');document.body.classList.remove('dialog-presenting')}

  $('#teacher-login-form').addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());setStatus('#teacher-login-status','Menyemak akses…');try{auth={email:fd.teacherEmail.trim(),pin:fd.teacherPin};localStorage.setItem('sapTeacherEmail',auth.email);await loadWorkspace();$('#teacher-login-panel').classList.add('hidden');$('#teacher-workspace-panel').classList.remove('hidden');setStatus('#teacher-login-status','')}catch(err){auth=null;setStatus('#teacher-login-status',err.message,true)}});
  $('#teacher-login-form').teacherEmail.value=localStorage.getItem('sapTeacherEmail')||'';
  $('#btn-teacher-logout').onclick=()=>{auth=null;workspace={groups:[],individuals:[],programs:[],dialogTasks:[]};$('#teacher-workspace-panel').classList.add('hidden');$('#teacher-login-panel').classList.remove('hidden')};
  document.querySelectorAll('.workspace-tab').forEach(b=>b.onclick=()=>{activeTab=b.dataset.workspaceTab;renderWorkspace()});
  $('#btn-prepare-dialog').onclick=openDialogBuilder;$('#dialog-builder-close').onclick=closeDialogBuilder;$('[data-close-dialog-builder]').onclick=closeDialogBuilder;$('#btn-select-core').onclick=()=>$('#dialog-subject-options').querySelectorAll('input').forEach(x=>x.checked=coreSubjects.includes(String(x.value).toUpperCase()));$('#btn-generate-dialog').onclick=generateDialog;$('#btn-dialog-prev').onclick=()=>{if(slideIndex>0){slideIndex--;showSlide()}};$('#btn-dialog-next').onclick=()=>{if(slideIndex<slides.length-1){slideIndex++;showSlide()}};$('#btn-dialog-exit').onclick=exitPresentation;$('#btn-dialog-print').onclick=printDialog;window.addEventListener('afterprint',()=>{if(document.body.classList.contains('dialog-print-all')){document.body.classList.remove('dialog-print-all');showSlide()}});
  window.addEventListener('sap-data-ready',e=>{portal=e.detail||portal});if(window.SAP_TEMIN_PORTAL_DATA)portal={...portal,...window.SAP_TEMIN_PORTAL_DATA};
})();
